### ISSUE TITLE
Internal bridging issue on z_drive_main parts

### ISSUE THREAD

**Issue by Jasrags** [AndrewEllis93/Ellis-PIF-Profile#3] opened 2021-10-30 00:03 UTC
First off thanks for the profiles, they have been great in helping me understand the more advanced tuning i needed to do to push my profiles forward.

I just ran into a strange issue using your standard profile that i wanted to share and see if it's a problem on your side as well. 

Steps to reproduce:

1. Using SS .57.0 or .57.3
1. Load and slice `z_drive_main_b_x2.stl`

<img width="1005" alt="Screen Shot 2021-10-29 at 6 53 30 PM" src="https://user-images.githubusercontent.com/131606/139512539-abae43b8-8bcd-475a-98cc-de79b7c0db6c.png">
<img width="972" alt="Screen Shot 2021-10-29 at 6 53 44 PM" src="https://user-images.githubusercontent.com/131606/139512550-ef94ec17-f1e9-4287-9367-58e6f6b7c9c2.png">
![IMG_5726](https://user-images.githubusercontent.com/131606/139512665-8043ae5d-857e-4c16-acef-85556556ce5b.jpg)

What seems to be happening is due to the `180%` infill extrusion width the slicer is unable to complete the infill and decides to use `Internal Bridge Infill`. 

Fix:
Reduce `Internal Bridge Infill` <= `160%`

I'm in no way saying this is not a super slicer issue, but i wanted to raise it to you as well to see if you have it on your prints or you know of any other way to solve for this. 

**Note**: Some modifications have been made during the tuning of my printer but nothing in the width section.

3MF file: [z_drive_main_a_x2.3mf.zip](https://github.com/AndrewEllis93/Ellis-PIF-Profile/files/7445426/z_drive_main_a_x2.3mf.zip)

**Comment by AndrewEllis93** [comment] 2021-10-30 00:27
I'm not quite sure I understand what the issue is. Can you circle the issue in your example photos? Do you mean that little corner in one of the two cutouts with the bridging?
And I don't see a setting called "internal bridge infill", though I do see it as an extrusion type in the preview.

**Comment by Jasrags** [comment] 2021-10-30 01:23
Hey, sorry i should have done that at first. It happens at layer 17 (3.45mm z). 

<img width="1361" alt="Screen Shot 2021-10-29 at 8 21 29 PM" src="https://user-images.githubusercontent.com/131606/139515332-7ff17cf5-f46b-461d-8708-eaea74fe17df.png">

**Comment by Jasrags** [comment] 2021-10-30 01:25
There is no setting for internal bridge infill as far as i can see, i think it's just one of those strange slicer issues with line widths but i just wanted to raise it to you as it might be happening for others with these settings.

**Comment by Jasrags** [comment] 2021-10-30 01:25
Also i see another typo the width is `Infill: width` not what i said before.

**Comment by AndrewEllis93** [comment] 2021-11-19 19:53
This appears to have been resolved with today's change / the new SS version:

2021-11-19: Set new bridge_overlap_min setting to 50%
- Fixes 50% bridge density in new SuperSlicer version (2.3.57.6).

**Closed** 2022-01-05 06:06 UTC
